### ISSUE TITLE
Error when user model is not using the SoftDelete trait

### ISSUE THREAD

**Issue by Lirux** [kenarkose/Chronicle#2]
Just encountered an problem when user model is not using the SoftDelete trait.
I think in the user method of the Activity class should check if the SoftDelete trait is used before using withTrashed().

```/**
     * User relation for the activity
     *
     * @return User
     */
    public function user()
    {
        return $this->belongsTo(
            $this->getUserModelName()
        )->withTrashed();
    }

**Comment by Hyleeh** [comment]
Hi, I applied the solution that you have suggested in the latest release, enjoy :)

**Comment by Lirux** [comment]
Thanks. It's working.
